#!/bin/bash
set -e

if [ ! -f /var/www/html/extensions/SemanticMediaWiki/.smw.json ]; then
    php /var/www/html/maintenance/update.php --skip-external-dependencies --quick
fi

apachectl -D FOREGROUND
