version: '3'
services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${VERSION}
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      CRON_INTERVAL: "*/1 * * * *"
    entrypoint: [ "sh", "/scripts/run.sh" ]
    volumes:
      - ./database:/var/lib/mysql
      - ./backup:/backup
    image: "uniwuezpd/mariadb-backup:${VERSION}"
