services:
  smw:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${SMW_IMAGE_TAG:-1.39.10}
    image: "uniwuezpd/${SMW_IMAGE_NAME:?error}:${SMW_IMAGE_TAG:-1.39.10}"
    ports:
      - "127.0.0.1:${SMW_PORT:-8080}:80"
    links:
      - database
    volumes:
      - ./wiki-images:/var/www/html/images
      # After initial setup, download LocalSettings.php to this repo and uncomment the following line
      # use docker-compose to restart the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
    depends_on:
      - database
    restart: always
    entrypoint: ["runWiki"]
  database:
    image: mariadb:11.1.4
    environment:
      MYSQL_DATABASE: "${DB_NAME:?error}"
      MYSQL_USER: "${DB_USER:?error}"
      MYSQL_PASSWORD: "${DB_PASSWORD:?error}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./db_data:/var/lib/mysql
      # In case you want to import a database dump uncomment the following line and point to the correct path on your host
      # - ./backup.sql:/docker-entrypoint-initdb.d/datadump.sql
    restart: always
  database-backup:
    image: uniwuezpd/mariadb-backup:11.1.4
    environment:
      MYSQL_DATABASE: "${DB_NAME:?error}"
      MYSQL_USER: "${DB_USER:?error}"
      MYSQL_PASSWORD: "${DB_PASSWORD:?error}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      CRON_INTERVAL: "${DB_BACKUP_CRON:-00 23 * * *}"
    entrypoint: [ "sh", "/scripts/runWiki.sh" ]
    volumes:
      - ./db_data:/var/lib/mysql
      - ./backup:/backup
    depends_on:
      - database
    restart: always
