version: '3.9'

services:
  smw:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${IMAGE_TAG}
    image: "uniwuezpd/${IMAGE_NAME}:${IMAGE_TAG}"
    ports:
      - "127.0.0.1:${SMW_PORT}:80"
    links:
      - database
    volumes:
      - wiki-images:/var/www/html/images
      # After initial setup, download LocalSettings.php to this repo and uncomment the following line
      # use docker-compose to restart the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
    depends_on:
      - database
  smw-cron:
    image: "uniwuezpd/${IMAGE_NAME}:${IMAGE_TAG}"
    links:
      - database
    volumes:
      - wiki-images:/var/www/html/images
      # After initial setup, download LocalSettings.php to this repo and uncomment the following line
      # use docker-compose to restart the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
    depends_on:
      - smw
    entrypoint: ["cron", "-f"]
  database:
    image: mariadb:11.1.4
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./database:/var/lib/mysql
  database-backup:
    image: uniwuezpd/mariadb-backup:11.1.4
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    entrypoint: ["cron", "-f"]
    volumes:
      - ./database:/var/lib/mysql
      - ./backup:/backup
    depends_on:
      - database

volumes:
  wiki-images:
