version: '3'
services:
  smw:
    build:
      context: .
      dockerfile: Dockerfile
    image: "uniwuezpd/smw:${IMAGE_TAG}"
    restart: always
    ports:
      - "127.0.0.1:${SMW_PORT}:80"
    links:
      - database
    volumes:
      - wiki-images:/var/www/html/images
      # After initial setup, download LocalSettings.php to this repo and uncomment the following line
      # use docker-compose to restart the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
  database:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
volumes:
  wiki-images:
