name: Build and Push Docker image for the base image

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/1.39/base/**'

jobs:
  read-env-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read .env file
        id: dotenv
        run: |
          echo "ENV_VARS<<EOF" >> $GITHUB_OUTPUT
          cat images/base/.env >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Set environment variables
        run: |
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^#.*$ ]] && [[ ! -z "$line" ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done <<< "${{ steps.dotenv.outputs.ENV_VARS }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: images/base
          push: true
          tags: uniwuezpd/smw-base:${{ env.VERSION }}
